name: lab-final
on:
  push:
    branches:
      - feature-lab-final

jobs:

  SAST:
    runs-on: ubuntu-latest
    steps:
      # Configuración del repositorio
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configuración de la versión de Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      # Instalar dependencias
      - name: Instalar dependencias
        run: npm install

      # Construir el proyecto
      - name: Construir el proyecto
        run: npm run build
      
      # Configurar SonarCloud
      - name: Configurar SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ github.repository }} \
            -Dsonar.organization=wladimirluna \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.projectName=${{ github.repository }} \
            -Dsonar.sources=. \
            -Dsonar.language=js \
            -Dsonar.sourceEncoding=UTF-8 \
            || echo "Skipping SonarCloud analysis: possible project setup issue"

      # Analizar el código con SonarCloud
      - name: Analizar código en SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ github.repository }} \
            -Dsonar.organization=wladimirluna \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

