name: lab-final
on:
  push:
    branches:
      - feature-lab-final

jobs:

  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "Compilación"

  TEST:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Pruebas"

  DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Despliegue"

    
        
