name: lab-final
on:
  push:
    branches:
      - feature-lab-final

jobs:

  SAST:
    runs-on: ubuntu-latest
    steps:
      # Configuración del repositorio
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configuración de la versión de Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      # Instalar dependencias
      - name: Instalar dependencias
        run: npm install

      # Construir el proyecto
      - name: Construir el proyecto
        run: npm run build

      # Instalar Java 17
      - name: Instalar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # Instalar SonarScanner
      - name: Instalar SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner-cli-4.7.0.2747-linux.zip
          sudo mv sonar-scanner-4.7.0.2747-linux /usr/local/sonar-scanner
          sudo ln -s /usr/local/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

      # Configurar SonarCloud
      - name: Configurar SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ github.repository }} \
            -Dsonar.organization=wladimirluna \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.projectName=${{ github.repository }} \
            -Dsonar.sources=. \
            -Dsonar.language=js \
            -Dsonar.sourceEncoding=UTF-8 \
            || echo "Skipping SonarCloud analysis: possible project setup issue"

      # Analizar el código con SonarCloud
      - name: Analizar código en SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ github.repository }} \
            -Dsonar.organization=wladimirluna \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

